### ISSUE TITLE
Fasapay Credential

### ISSUE THREAD

**Issue by vintots** [andreas22/omnipay-fasapay#1]
where can i put Fasapay credentials like this 

'paypal' => [
            'driver'  => 'PayPal_Express',
            'options' => [
                'username'  => env( 'OMNIPAY_PAYPAL_EXPRESS_USERNAME', '' ),
                'password'  => env( 'OMNIPAY_PAYPAL_EXPRESS_PASSWORD', '' ),
                'signature' => env( 'OMNIPAY_PAYPAL_EXPRESS_SIGNATURE', '' ),
                'testMode' => env( 'OMNIPAY_PAYPAL_EXPRESS_TEST_MODE', '' ),
                'solutionType'   => '',
                'landingPage'    => '',
                'headerImageUrl' => ''
            ]
        ]

for me to integrate Fasapay in ignited/laravel-omnipay

**Comment by andreas22** [comment]
I have not used package ignited/laravel-omnipay, but I think that you can store them after your paypal configuration and then upon initialization you fetch the config.

**Comment by vintots** [comment]
i already solved it using this code

 // Example form data
  $gateway = Omnipay::create('Fasapay');
        $purchaseOptions = array(
         'accountTo' => 'accountto',
         'accountFrom' => 'accountfrom',
         'item' => 'MyItem',
         'amount' => 1000.0,
         'currency' => 'IDR',
         'comments' => 'No comment',
         'transactionId' => '1311059196',
         'returnUrl' => url('test-payment-success-fasapay'),  //Success url
         'successMethod' => 'GET',
         'cancelUrl' => url(),  //Cancel url
         'failMethod' => 'GET',
         'notifyUrl' => url('test-payment-success-fasapay'),  //Callback url - server to server
         'statusMethod' => 'POST',
        );

```
    $response = $gateway->purchase($purchaseOptions)->setTestMode(true)->send();
```

Thanks for the response , my problem now is  can't get its 

$response->getTransactionReference() right after i used completePurchase() function

**Comment by andreas22** [comment]
If you follow up the example in README, you should have a callback php file, then getTransactionReference will only be available if transaction is successful. See example https://github.com/andreas22/omnipay-fasapay#purchase-callback-simple-mode and let me know if you still have issues.
